### ISSUE TITLE
mongoose.c:9026:3: note: in expansion of macro 'sigemptyset'

### ISSUE THREAD

**Issue by EvanLyu** [younghyunjo/esp32-homekit#6]
I cloned a new repository.
I have some compilation errors on mongoose.c
My operating system is MacOS 10.13.3 and uses the latest ESP-IDF / esp32-homekit
What steps have I made wrong?

This error occurs the first time I use it, but it will not happen afterwards.
![2018-04-03 2 22 33](https://user-images.githubusercontent.com/6142091/38209549-49f01756-36e7-11e8-9ef8-128605649aaf.png)

![2018-04-03 2 22 44](https://user-images.githubusercontent.com/6142091/38209561-547fccde-36e7-11e8-8b73-2a9d478379f9.png)
![2018-04-03 2 24 01](https://user-images.githubusercontent.com/6142091/38209562-54aad74e-36e7-11e8-89f2-a91edb025380.png)

**Comment by younghyunjo** [comment]
I am working with ubuntu16.04, lastest ESP_IDF and xtensa-esp32-elf-1.22.0-75 toolchain.
```
commit aca000869406e35eba0d5fd7064304ba9e5acead
Merge: 8eaae96 d6b1d0b
Author: Ivan Grokhotkov <ivan@espressif.com>
Date:   Mon Apr 2 13:48:46 2018 +0800

    Merge branch 'bugfix/sdspi_init_v1_card' into 'master'
    
    sdspi: compatibility fixes for SD v1.0 cards
    
    See merge request idf/esp-idf!1927

```
I am not sure the exact reason 
but I think the reason seems like toolchain
please check your toolchain version

**Comment by EvanLyu** [comment]
Thanks.
I downgrade toolchain to xtensa-esp32-elf-1.22.0-75 and upgrade mongoose to 6.11 .
Build success on my mac 10.13.3

**Comment by younghyunjo** [comment]
I upgraded mongoose to 6.11 in master branch

**Comment by jjoe64** [comment]
I had the same error and I just had to run `make all` to fix it
